autoinstall:
  version: 1
  interactive-sections:
    - identity
    - storage
  early-commands:
    - wget -q -O /bootaa64.efi https://github.com/0mniteck/U-Boot/raw/refs/heads/Docker/Deploy/ubuntu/bootaa64.efi
    - echo "3c7b02add63da9f1d76096dfd6aacc13d2ab5fec7a0ac820a752512aab7d80374a0ea463611473bf9e15c8bb3cc35e85a6d93433d6709a88995f2e17bf476fca  /bootaa64.efi" | sha512sum --status -c - && echo "bootaa64.efi Checksum Matched!" || poweroff
    - wget -q -O /shimaa64.efi https://github.com/0mniteck/U-Boot/raw/refs/heads/Docker/Deploy/ubuntu/shimaa64.efi
    - echo "cd332972c26369600cf9ce7b3373977c4674794e8b80eaf36fe53d08fc9abc746bb1739cbb6e31d55aacf0a13705302d7b7d73d251c86754d9416c4d1673ef35  /shimaa64.efi" | sha512sum --status -c - && echo "shimaa64.efi Checksum Matched!" || poweroff
  locale: "en_US.UTF-8"
  refresh-installer:
    update: true
    channel: "stable/ubuntu-$REL"
  keyboard:
    layout: us
    variant: ""
    toggle: null
  source:
    search_drivers: false
    id: ubuntu-desktop-minimal
  network:
    version: 2
    ethernets:
      end0:
        dhcp6: true
  proxy: null
  apt:
    preserve_sources_list: false
    mirror-selection:
      primary:
        - uri: "https://us.ports.ubuntu.com/ubuntu-ports"
          arches: [arm64]
      sources_list: |
        URIs: $PRIMARY
        Suites: $RELEASE $RELEASE-updates $RELEASE-security $RELEASE-backports
        Components: main
    fallback: abort
    geoip: false
  autoinstall:
  storage:
    layout:
      name: lvm
      sizing-policy: all
      match:
        - path: /dev/mmcblk0
  ubuntu-pro:
    token:
  active-directory:
    admin-name: ""
    domain-name: ""
  ssh:
    install-server: false
    authorized-keys: []
    allow-pw: false
  codecs:
    install: false
  drivers:
    install: false
  oem:
    install: false
  snaps:
    - name: chromium
      channel: stable
      classic: false
    - name: ufw
      channel: stable
      classic: false
  debconf-selections: |
    ufw ufw/enable boolean true
  packages:
    - libpam-u2f
    - dracut
    - fido2-tools
  kernel:
     flavor: generic
  kernel-crash-dumps:
     enabled: false
  timezone: "America/Los_Angeles"
  updates: all
  shutdown: poweroff
  late-commands:
    - curtin in-target -- apt-get remove --purge ufw firefox
    - curtin in-target -- apt-mark hold shim shim-signed
    - cp /bootaa64.efi /target/boot/efi/EFI/BOOT/BOOTAA64.EFI
    - echo "3c7b02add63da9f1d76096dfd6aacc13d2ab5fec7a0ac820a752512aab7d80374a0ea463611473bf9e15c8bb3cc35e85a6d93433d6709a88995f2e17bf476fca  /target/boot/efi/EFI/BOOT/BOOTAA64.EFI" | sha512sum --status -c - && echo "bootaa64.efi Checksum Matched!" || exit 1
    - cp /shimaa64.efi /target/boot/efi/EFI/ubuntu/shimaa64.efi
    - echo "cd332972c26369600cf9ce7b3373977c4674794e8b80eaf36fe53d08fc9abc746bb1739cbb6e31d55aacf0a13705302d7b7d73d251c86754d9416c4d1673ef35  /target/boot/efi/EFI/ubuntu/shimaa64.efi" | sha512sum --status -c - && echo "shimaa64.efi Checksum Matched!" || exit 1
    - curtin in-target -- curl -fsSL https://pkg.cloudflareclient.com/pubkey.gpg | gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
    - curtin in-target -- echo "deb [signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ noble main" | tee /etc/apt/sources.list.d/cloudflare-client.list
    - curtin in-target -- apt update
    - curtin in-target -- apt install cloudflare-warp
    - curtin in-target -- warp-cli registration new
    - curtin in-target -- warp-cli mode warp+doh
    - curtin in-target -- warp-cli dns families malware
    - curtin in-target -- warp-cli connect
    - sleep 5m
  error-commands:
    - tar -czf /target/installer-logs.tar.gz /var/log/installer/
    - journalctl -b > /target/installer-journal.error.log
  reporting:
    builtin:
      type: none
  user-data: {}
