autoinstall:
  version: 1
  interactive-sections:
    - identity
    - storage
  early-commands:
    - wget -q -O /bootaa64.efi https://github.com/0mniteck/U-Boot/raw/refs/heads/Docker/Deploy/ubuntu/bootaa64.efi
    - echo "3c7b02add63da9f1d76096dfd6aacc13d2ab5fec7a0ac820a752512aab7d80374a0ea463611473bf9e15c8bb3cc35e85a6d93433d6709a88995f2e17bf476fca  /bootaa64.efi" | sha512sum --status -c - && echo "bootaa64.efi Checksum Matched!" || poweroff
    - wget -q -O /shimaa64.efi https://github.com/0mniteck/U-Boot/raw/refs/heads/Docker/Deploy/ubuntu/shimaa64.efi
    - echo "cd332972c26369600cf9ce7b3373977c4674794e8b80eaf36fe53d08fc9abc746bb1739cbb6e31d55aacf0a13705302d7b7d73d251c86754d9416c4d1673ef35  /shimaa64.efi" | sha512sum --status -c - && echo "shimaa64.efi Checksum Matched!" || poweroff
  locale: "en_US.UTF-8"
  refresh-installer:
    update: true
    channel: "stable/ubuntu-$REL"
  keyboard:
    layout: us
    variant: ""
    toggle: null
  source:
    search_drivers: false
    id: ubuntu-desktop-minimal
  network:
    version: 2
    ethernets:
      end0:
        dhcp6: true
  proxy: null
  apt:
    preserve_sources_list: false
    disable_components: [restricted, universe, multiverse]
    mirror-selection:
      primary:
        - uri: "https://us.ports.ubuntu.com/ubuntu-ports"
          arches: [arm64, default]
          fallback:
            primary: "https://us.ports.ubuntu.com/ubuntu-ports"
            security: "https://us.ports.ubuntu.com/ubuntu-ports"
      sources_list: |
        URIs: $PRIMARY
        Suites: $RELEASE $RELEASE-updates $RELEASE-backports
        Components: main
        |
        URIs: $SECURITY
        Suites: $RELEASE-security
        Components: main
    sources:
      cloudflare.sources:
        source: |
          Types: deb
          URIs: https://pkg.cloudflareclient.com/
          Suites: noble
          Components: main
          key: |
            -----BEGIN PGP PUBLIC KEY BLOCK-----
            
            mQINBGGr2jUBEADHaae1uIKW4JI/E32IR9EJSswkOuZl1J+XXH32U2u3DGtzGuei
            dNXyeQ7AWHp5bM2wO7jGRqH/IwiDVHzp6gmJ8r/SFrE+iljNA71LVXY7FjaOGmKC
            pZnzl3mlY9zsRgmM+oEbTedg2k1jfeHWiYJfTk4efDUGNqF4D62GBFLpOheeXtNU
            DHuZjcRBFKO3wjt3wPpuUx+/NoHrxWK2HZxL6cHUHxmqOHlemGAvZug0pkeAWaAb
            YYmlwsi9/KbnZ22poCfubCebeLIIC4GrQd5ZdJn3efa1ps41gHG/s0RpoQvC128x
            ZQDfdjskuXA0IlDUwzGK2qeY2PEbHpPAH02cm2JrO0NkVBO/4tJ3QkrBRdkOoS1C
            PZRFkzaamA7kZb03wHHLqMZ4lpw+Aa4w0jihndQUvxi9HQVmzjYW1HeQXHmVPdNc
            MT6Y/XxFUFfz65zpZy6s5e8250yIaiNtTuvpcXebmkx0uM4naQFjSJTTlrNeXM/L
            67JppgInRXwlaevNBTm24HhJy0zef1Gpnt6xJDtCX2qNg0GhbuJXbFhgSF1Ct7eY
            tZsfx6UbEXdkwEtcrIAXIqrVjenqcvh8w47I06rqKEoiMliQxh/WrIjTDCsIq/LB
            ki820eS6GsJ5N2JmZ2CQ7Kt+y/Gx9uMDmUcCnHY10vX+Va66/GKMX+vbKQARAQAB
            tDZDbG91ZGZsYXJlIFBhY2thZ2UgUmVwb3NpdG9yeSA8c3VwcG9ydEBjbG91ZGZs
            YXJlLmNvbT6JAlgEEwEIAEIWIQTAaKK1dxd1GTy+Hy9uLdIXT6HDugUCYavaNQIb
            AwUJB4TOAAULCQgHAgMiAgEGFQoJCAsCBBYCAwECHgcCF4AACgkQbi3SF0+hw7oC
            IA/+IZBUh2rWq62WHQ55IGbruVL8MPBOgYb9nikxMjxlqxBjy+A61aS+KgdgdhTk
            dal06iRLUIGNJ8P9W2eSPmxX6R3R5s+r7bwn8eb5pY8voW93FE6LX2klLGdafckL
            7USOqQzgcrtKqVSHNokzx4mKxreJzvB5Xef+dj3jNe8Xoxzp3QjUk17Zbq1jg1cS
            umDTXJVJqtkbhgUl9xyfMst8ShiBMV0UCUUrXDaMw9eoQ1cmk6D/VzgrTOk8qLjg
            nvA4Zop8un5tQXWiKmWu/oaK+hKZCQKgZuJWmA6PVpee1m6uGXoxItCA9dIRKj4X
            NsyVp7r95hZ2R1uiu2vmbHaWLibMTOcDD3ZQ4Fxuh7Aozpq1AemCy2L7uv6j79TP
            x5JuUkKT+DUp2ZPlBML5E0xWShuEEPF2InIFqpePmkB2HHQ2jMY0067szv3bjVar
            qF6FQM+1x9XYf/NpxQbb/DIhR2JQzcR4dftPERPp3ZfmKVzX6x/pkXgYXS4AqUeb
            +QE7dSlOf2KxVdBJSBSktGyA1jlOGDKD7DKP1tF+HNcRZd/avC6iFBK/sNYpUZBD
            iY0cWM0XC7CORUVPMLcvLBtojgI6BbXqva7UsltkwZ1tPbTF53JsgdfzMbkkQ2zi
            yYtPawgLR07KlstXanuMbJwuLg0j/1dLWPV1ddC/oUHjog4=
            =J+JK
            -----END PGP PUBLIC KEY BLOCK-----
    fallback: abort
    geoip: true
  storage:
    layout:
      name: lvm
      sizing-policy: all
      encrypted: yes
      match:
        - path: /dev/mmcblk0
  ubuntu-pro:
  active-directory:
    admin-name: ""
    domain-name: ""
  ssh:
    install-server: false
    authorized-keys: []
    allow-pw: false
  codecs:
    install: false
  drivers:
    install: false
  oem:
    install: false
  snaps:
    - name: chromium
      channel: stable
      classic: false
    - name: ufw
      channel: stable
      classic: false
  debconf-selections: |
    ufw ufw/enable boolean true
  packages:
    - cloudflare-warp
    - libpam-u2f
    - fido2-tools
    - dracut
  kernel:
     flavor: generic
  kernel-crash-dumps:
     enabled: false
  timezone: "America/Los_Angeles"
  updates: all
  shutdown: poweroff
  late-commands:
    - curtin in-target -- apt install device-tree-compiler devio libfdt1 libiniparser1 libubootenv-tool u-boot-tools mtd-utils -y
    - curtin in-target -- apt remove --purge ufw firefox -y
    - curtin in-target -- apt-mark hold shim shim-signed
    - cp /bootaa64.efi /target/boot/efi/EFI/BOOT/BOOTAA64.EFI
    - echo "3c7b02add63da9f1d76096dfd6aacc13d2ab5fec7a0ac820a752512aab7d80374a0ea463611473bf9e15c8bb3cc35e85a6d93433d6709a88995f2e17bf476fca  /target/boot/efi/EFI/BOOT/BOOTAA64.EFI" | sha512sum --status -c - && echo "bootaa64.efi Checksum Matched!" || exit 1
    - cp /shimaa64.efi /target/boot/efi/EFI/ubuntu/shimaa64.efi
    - echo "cd332972c26369600cf9ce7b3373977c4674794e8b80eaf36fe53d08fc9abc746bb1739cbb6e31d55aacf0a13705302d7b7d73d251c86754d9416c4d1673ef35  /target/boot/efi/EFI/ubuntu/shimaa64.efi" | sha512sum --status -c - && echo "shimaa64.efi Checksum Matched!" || exit 1
    - curtin in-target -- warp-cli registration new
    - curtin in-target -- warp-cli mode warp+doh
    - curtin in-target -- warp-cli dns families malware
    - curtin in-target -- warp-cli connect
    - sleep 5m
  error-commands:
    - tar -czf /target/installer-logs.tar.gz /var/log/installer/
    - journalctl -b > /target/installer-journal.error.log
  reporting:
    builtin:
      type: none
  user-data: {}
